/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Link } from "./components/quake-render/quake-render";
export namespace Components {
    interface EmbedLink {
        "entryId": number;
        "entryType": string;
    }
    interface QuakeGraph {
        "config": any;
        "data": any;
    }
    interface QuakeRender {
        "content": string;
        "hasEmbed": boolean;
    }
}
declare global {
    interface HTMLEmbedLinkElement extends Components.EmbedLink, HTMLStencilElement {
    }
    var HTMLEmbedLinkElement: {
        prototype: HTMLEmbedLinkElement;
        new (): HTMLEmbedLinkElement;
    };
    interface HTMLQuakeGraphElement extends Components.QuakeGraph, HTMLStencilElement {
    }
    var HTMLQuakeGraphElement: {
        prototype: HTMLQuakeGraphElement;
        new (): HTMLQuakeGraphElement;
    };
    interface HTMLQuakeRenderElement extends Components.QuakeRender, HTMLStencilElement {
    }
    var HTMLQuakeRenderElement: {
        prototype: HTMLQuakeRenderElement;
        new (): HTMLQuakeRenderElement;
    };
    interface HTMLElementTagNameMap {
        "embed-link": HTMLEmbedLinkElement;
        "quake-graph": HTMLQuakeGraphElement;
        "quake-render": HTMLQuakeRenderElement;
    }
}
declare namespace LocalJSX {
    interface EmbedLink {
        "entryId"?: number;
        "entryType"?: string;
    }
    interface QuakeGraph {
        "config"?: any;
        "data"?: any;
    }
    interface QuakeRender {
        "content"?: string;
        "hasEmbed"?: boolean;
        "onClickEmbedLink"?: (event: CustomEvent<Link>) => void;
        "onClickPageLink"?: (event: CustomEvent<Link>) => void;
    }
    interface IntrinsicElements {
        "embed-link": EmbedLink;
        "quake-graph": QuakeGraph;
        "quake-render": QuakeRender;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "embed-link": LocalJSX.EmbedLink & JSXBase.HTMLAttributes<HTMLEmbedLinkElement>;
            "quake-graph": LocalJSX.QuakeGraph & JSXBase.HTMLAttributes<HTMLQuakeGraphElement>;
            "quake-render": LocalJSX.QuakeRender & JSXBase.HTMLAttributes<HTMLQuakeRenderElement>;
        }
    }
}
